/*
 * 아이코노그래피 레지스트리 — food-recommend-design.pen의 I/* 컴포넌트와 1:1.
 * 디자인 아이콘명 → 라이브러리 컴포넌트 매핑. 아웃라인은 lucide, 필은 phosphor(fill).
 */
import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  House,
  Calendar,
  Copy,
  RefreshCw,
  LogOut,
  X,
  Menu,
  Search,
  Funnel,
  ArrowUpDown,
  Plus,
  SquarePen,
  Trash2,
  Bookmark,
  Share,
  Ellipsis,
  EllipsisVertical,
  Check,
  Info,
  TriangleAlert,
  CircleAlert,
  User,
  Settings,
  Bell,
  Heart,
  Star,
  MessageSquare,
  Image,
  Wifi,
  Signal,
  BatteryFull,
  BatteryLow,
  Play,
  Camera,
  Link,
  Languages,
  SlidersHorizontal,
  MessageCircle,
  CircleCheck,
  CirclePlus,
  ThumbsUp,
  HandHeart,
  Sparkles,
  Lightbulb,
  ShieldCheck,
  Ban,
  ClockAlert,
  Scale,
  Wallet,
  ReceiptText,
  Refrigerator,
  ChefHat,
  Utensils,
  Flame,
  Timer,
  Leaf,
  type LucideIcon,
} from "lucide-react";
import {
  House as PhHouse,
  MagnifyingGlass as PhMagnifyingGlass,
  Calendar as PhCalendar,
  User as PhUser,
  Bookmark as PhBookmark,
  Heart as PhHeart,
  Star as PhStar,
  Bell as PhBell,
  Gear as PhGear,
  ChatCircle as PhChatCircle,
  CheckCircle as PhCheckCircle,
  PlusCircle as PhPlusCircle,
  Play as PhPlay,
  Image as PhImage,
  Fire as PhFire,
  Leaf as PhLeaf,
  type Icon as PhosphorIcon,
} from "@phosphor-icons/react";

export const outlineIcons = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  home: House,
  calendar: Calendar,
  copy: Copy,
  refresh: RefreshCw,
  logout: LogOut,
  close: X,
  menu: Menu,
  search: Search,
  filter: Funnel,
  sort: ArrowUpDown,
  plus: Plus,
  edit: SquarePen,
  delete: Trash2,
  bookmark: Bookmark,
  share: Share,
  "more-horizontal": Ellipsis,
  "more-vertical": EllipsisVertical,
  check: Check,
  info: Info,
  warning: TriangleAlert,
  error: CircleAlert,
  user: User,
  settings: Settings,
  notification: Bell,
  heart: Heart,
  star: Star,
  comment: MessageSquare,
  image: Image,
  wifi: Wifi,
  signal: Signal,
  "battery-full": BatteryFull,
  "battery-low": BatteryLow,
  play: Play,
  camera: Camera,
  link: Link,
  languages: Languages,
  "sliders-horizontal": SlidersHorizontal,
  "message-circle": MessageCircle,
  "circle-check": CircleCheck,
  "circle-plus": CirclePlus,
  "thumbs-up": ThumbsUp,
  "hand-heart": HandHeart,
  sparkles: Sparkles,
  lightbulb: Lightbulb,
  "shield-check": ShieldCheck,
  ban: Ban,
  "clock-alert": ClockAlert,
  scale: Scale,
  wallet: Wallet,
  "receipt-text": ReceiptText,
  refrigerator: Refrigerator,
  "chef-hat": ChefHat,
  utensils: Utensils,
  flame: Flame,
  timer: Timer,
  leaf: Leaf,
} satisfies Record<string, LucideIcon>;

export const fillIcons = {
  "home-fill": PhHouse,
  "search-fill": PhMagnifyingGlass,
  "calendar-fill": PhCalendar,
  "user-fill": PhUser,
  "bookmark-fill": PhBookmark,
  "heart-fill": PhHeart,
  "star-fill": PhStar,
  "notification-fill": PhBell,
  "settings-fill": PhGear,
  "comment-fill": PhChatCircle,
  "circle-check-fill": PhCheckCircle,
  "circle-plus-fill": PhPlusCircle,
  "play-fill": PhPlay,
  "image-fill": PhImage,
  "flame-fill": PhFire,
  "leaf-fill": PhLeaf,
} satisfies Record<string, PhosphorIcon>;

export const ICON_SIZES = [16, 20, 24, 32] as const;

export type OutlineIconName = keyof typeof outlineIcons;
export type FillIconName = keyof typeof fillIcons;
export type IconName = OutlineIconName | FillIconName;
export type IconSize = (typeof ICON_SIZES)[number];

export const outlineIconNames = Object.keys(outlineIcons) as OutlineIconName[];
export const fillIconNames = Object.keys(fillIcons) as FillIconName[];
